import os

TOKEN = os.getenv('DISCORD_TOKEN')

DB_HOST=os.getenv('DB_HOST')
DB_USER=os.getenv('DB_USER')
DB_PASS=os.getenv('DB_PASS')
DB_NAME=os.getenv('DB_NAME')
APP_KEY=os.getenv('APP_KEY')
PUSHER_APP_ID=os.getenv('PUSHER_APP_ID')
PUSHER_APP_KEY=os.getenv('PUSHER_APP_KEY')
PUSHER_APP_SECRET=os.getenv('PUSHER_APP_SECRET')


f = open('/app/.env', 'w')

f.write('APP_NAME=BFACP\n')
f.write(f'APP_KEY={APP_KEY}\n')
f.write('APP_URL=http://localhost\n')
f.write(f'DB_HOST={DB_HOST}\n')
f.write(f'DB_DATABASE={DB_NAME}\n')
f.write(f'DB_USERNAME={DB_USER}\n')
f.write(f'DB_PASSWORD={DB_PASS}\n')
f.write('IP_WHITELIST=127.0.0.1\n')
f.write(f'PUSHER_APP_ID={PUSHER_APP_ID}\n')
f.write(f'PUSHER_KEY={PUSHER_APP_KEY}\n')
f.write(f'PUSHER_SECRET={PUSHER_APP_SECRET}\n')
f.write('PUSHER_CLUSTER=mt1\n')
f.write('MAIL_DRIVER=mailgun\n')
f.write('MAILGUN_DOMAIN=\n')
f.write('MAILGUN_SECRET=\n')
f.write('BROADCAST_DRIVER=memcached\n')
f.write('CACHE_DRIVER=memcached\n')
f.write('QUEUE_CONNECTION=sync\n')
f.write('SESSION_DRIVER=memcached\n')
f.write('SESSION_LIFETIME=120\n')
f.write('REDIS_CLIENT=predis\n')
f.write('REDIS_HOST=127.0.0.1\n')
f.write('REDIS_PASSWORD=null\n')
f.write('REDIS_PORT=6379')